name: 'Pull Request Actions'

on:
  pull_request:
    # Only initiate the workflow when a PR is opened, or committed to.
    branches:
      - main

jobs:
  checkLintAndTest:
    name: 'Check, Lint, and Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.20.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Type Checking
        run: pnpm check

      - name: Run Linting
        run: pnpm lint

      - name: Run Tests
        run: pnpm test
